services:
  callis:
    build: .
    develop:
      watch:
        - action: sync+restart
          path: ./api
          target: /app
          ignore:
            - __pycache__/
            - "*.pyc"
            - uv.lock
        - action: rebuild
          path: ./api/pyproject.toml
