services:
  caddy:
    image: caddy:2.9
    profiles: ["caddy"]
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
    networks:
      - callis
    env_file: .env

volumes:
  caddy_data:
