[Definition]
failregex = ^.*Failed publickey for .* from <HOST> port \d+ ssh2$
            ^.*Connection closed by authenticating user .* <HOST> port \d+ \[preauth\]$
            ^.*Disconnected from authenticating user .* <HOST> port \d+ \[preauth\]$

ignoreregex =
